#!/usr/bin/env bash
# Install, verify, or remove an SSH-only Claude Code OAuth token wrapper.
#
# The token is stored as a single raw line in:
#   ~/.config/claude/ssh-oauth-token
#
# The managed zsh function injects CLAUDE_CODE_OAUTH_TOKEN only into the
# Claude process launched from an SSH shell. It never prints the token.

set -euo pipefail

readonly MANAGED_BEGIN="# >>> dotfiles claude-ssh-oauth >>>"
readonly MANAGED_END="# <<< dotfiles claude-ssh-oauth <<<"

COMMAND=""
TOKEN_SOURCE=""
DELETE_TOKEN=0

usage() {
  cat <<'EOF'
Usage:
  ssh-oauth-token.sh install [--token-file PATH]
  ssh-oauth-token.sh check
  ssh-oauth-token.sh uninstall [--delete-token]

Commands:
  install      Import a raw token or reuse the installed token, then install
               an idempotent SSH-only claude() wrapper in ~/.zshrc.
  check        Verify token permissions, managed markers, and zsh syntax.
  uninstall    Remove the managed wrapper. The token is retained unless
               --delete-token is explicitly passed.

Options:
  --token-file PATH  Import an existing single-line raw token without
                     displaying it. Used only by install.
  --delete-token     Also delete the installed token. Used only by uninstall.
  -h, --help         Show this help.

If install has no --token-file and no installed token, it securely prompts
for a token generated by `claude setup-token`.
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

note() {
  printf '%s\n' "$*"
}

require_supported_environment() {
  [ "$(uname -s)" = "Darwin" ] || die "this installer currently supports macOS only"
  [ -n "${HOME:-}" ] || die "HOME is not set"
  [ "${EUID:-$(id -u)}" -ne 0 ] || die "do not run this installer as root"
  [[ "$-" != *x* ]] || die "disable shell xtrace before handling credentials"
  command -v zsh >/dev/null 2>&1 || die "zsh is required"
}

validate_raw_token_file() {
  local path="$1"
  [ -f "$path" ] || die "token file is not a regular file: $path"
  [ -r "$path" ] || die "token file is not readable: $path"
  [ -s "$path" ] || die "token file is empty: $path"

  if ! LC_ALL=C awk '
    NR > 1 { exit 1 }
    NR == 1 && ($0 == "" || $0 ~ /[[:space:]]/) { exit 1 }
    END { if (NR != 1) exit 1 }
  ' "$path"; then
    die "token file must contain exactly one non-empty line without whitespace"
  fi

  if LC_ALL=C grep -q '^CLAUDE_CODE_OAUTH_TOKEN=' "$path"; then
    die "token file must contain only the raw token, not KEY=value"
  fi
}

token_mode() {
  stat -f '%Lp' "$1"
}

validate_token_permissions() {
  local path="$1"
  local mode
  mode="$(token_mode "$path")"
  if (( (8#$mode & 077) != 0 )); then
    die "token file permissions are too broad ($mode): $path"
  fi
}

resolve_symlink_target() {
  local path="$1"
  local link=""
  local directory=""
  local hops=0

  while [ -L "$path" ]; do
    hops=$((hops + 1))
    [ "$hops" -le 20 ] || die "too many symlink levels: $1"
    link="$(readlink "$path")"
    if [[ "$link" = /* ]]; then
      path="$link"
    else
      directory="$(cd -P "$(dirname "$path")" && pwd)"
      path="$directory/$link"
    fi
  done

  directory="$(cd -P "$(dirname "$path")" && pwd)"
  printf '%s/%s\n' "$directory" "$(basename "$path")"
}

install_token() {
  local destination="$1"
  local destination_dir
  local temporary=""
  local prompted_token=""

  destination_dir="$(dirname "$destination")"
  mkdir -p "$destination_dir"
  chmod go-rwx "$destination_dir"

  if [ -n "$TOKEN_SOURCE" ]; then
    TOKEN_SOURCE="$(cd "$(dirname "$TOKEN_SOURCE")" && pwd)/$(basename "$TOKEN_SOURCE")"
    validate_raw_token_file "$TOKEN_SOURCE"

    if [ "$TOKEN_SOURCE" != "$destination" ]; then
      temporary="$(mktemp "${destination}.tmp.XXXXXX")"
      trap 'rm -f "${temporary:-}"; unset prompted_token' EXIT
      cp "$TOKEN_SOURCE" "$temporary"
      chmod 600 "$temporary"
      mv "$temporary" "$destination"
      temporary=""
    fi
  elif [ -s "$destination" ]; then
    note "reusing installed token: $destination"
  else
    [ -t 0 ] || die "no token available; pass --token-file or run interactively"
    printf 'Claude SSH token: ' >&2
    IFS= read -r -s prompted_token
    printf '\n' >&2
    [ -n "$prompted_token" ] || die "token cannot be empty"
    [[ "$prompted_token" != *[[:space:]]* ]] ||
      die "token cannot contain whitespace"

    temporary="$(mktemp "${destination}.tmp.XXXXXX")"
    trap 'rm -f "${temporary:-}"; unset prompted_token' EXIT
    printf '%s\n' "$prompted_token" > "$temporary"
    unset prompted_token
    chmod 600 "$temporary"
    mv "$temporary" "$destination"
    temporary=""
  fi

  chmod 600 "$destination"
  validate_raw_token_file "$destination"
  validate_token_permissions "$destination"
  trap - EXIT
  note "installed token with mode 0600: $destination"
}

render_zsh_without_managed_block() {
  local source="$1"
  local output="$2"

  awk -v begin="$MANAGED_BEGIN" -v end="$MANAGED_END" '
    $0 == begin {
      if (inside) exit 20
      inside = 1
      next
    }
    $0 == end {
      if (!inside) exit 21
      inside = 0
      next
    }
    !inside { lines[++count] = $0 }
    END {
      if (inside) exit 22
      while (count > 0 && lines[count] == "") count--
      for (i = 1; i <= count; i++) print lines[i]
    }
  ' "$source" > "$output" ||
    die "malformed managed block in $source"
}

append_managed_zsh_block() {
  local output="$1"

  cat >> "$output" <<'EOF'

# >>> dotfiles claude-ssh-oauth >>>
# Use a long-lived OAuth token only for Claude Code launched over SSH.
claude() {
  local claude_bin
  claude_bin="$(whence -p claude)"

  if [[ -z "$claude_bin" ]]; then
    echo "Claude Code executable was not found in PATH." >&2
    return 127
  fi

  if [[ -z "${SSH_CONNECTION:-}" ]]; then
    command "$claude_bin" "$@"
    return
  fi

  local claude_ssh_token_file="$HOME/.config/claude/ssh-oauth-token"
  if [[ ! -r "$claude_ssh_token_file" ]]; then
    echo "Claude SSH token file is not readable: $claude_ssh_token_file" >&2
    return 1
  fi

  (
    export CLAUDE_CODE_OAUTH_TOKEN="$(<"$claude_ssh_token_file")"
    if [[ -z "$CLAUDE_CODE_OAUTH_TOKEN" ]]; then
      echo "Claude SSH token file is empty: $claude_ssh_token_file" >&2
      return 1
    fi

    export CLAUDE_CODE_SUBPROCESS_ENV_SCRUB="${CLAUDE_CODE_SUBPROCESS_ENV_SCRUB:-1}"
    command "$claude_bin" "$@"
  )
}
# <<< dotfiles claude-ssh-oauth <<<
EOF
}

backup_zshrc() {
  local zshrc="$1"
  local backup_base="$2"
  local backup

  backup="$(mktemp "${backup_base}.bak.$(date +%Y%m%d%H%M%S).XXXXXX")"
  cp -p "$zshrc" "$backup"
  printf '%s\n' "$backup"
}

install_zsh_wrapper() {
  local zshrc="$1"
  local backup_base="$2"
  local temporary
  local backup
  local mode

  if [ ! -e "$zshrc" ]; then
    umask 077
    : > "$zshrc"
  fi
  [ -f "$zshrc" ] || die "zshrc is not a regular file: $zshrc"

  temporary="$(mktemp "${zshrc}.tmp.XXXXXX")"
  trap 'rm -f "${temporary:-}"' EXIT
  render_zsh_without_managed_block "$zshrc" "$temporary"
  append_managed_zsh_block "$temporary"

  mode="$(stat -f '%Lp' "$zshrc")"
  chmod "$mode" "$temporary"
  zsh -n "$temporary" || die "generated zsh configuration failed syntax validation"

  if cmp -s "$zshrc" "$temporary"; then
    rm -f "$temporary"
    temporary=""
    trap - EXIT
    note "zsh wrapper already up to date: $zshrc"
    return
  fi

  backup="$(backup_zshrc "$zshrc" "$backup_base")"
  mv "$temporary" "$zshrc"
  temporary=""
  trap - EXIT
  note "installed SSH-only claude() wrapper: $zshrc"
  note "backup: $backup"
}

managed_marker_count() {
  local marker="$1"
  local zshrc="$2"
  grep -Fxc "$marker" "$zshrc" 2>/dev/null || true
}

check_installation() {
  local token_destination="$1"
  local zshrc="$2"
  local begin_count
  local end_count

  validate_raw_token_file "$token_destination"
  validate_token_permissions "$token_destination"
  [ -f "$zshrc" ] || die "zshrc is missing: $zshrc"

  begin_count="$(managed_marker_count "$MANAGED_BEGIN" "$zshrc")"
  end_count="$(managed_marker_count "$MANAGED_END" "$zshrc")"
  [ "$begin_count" -eq 1 ] ||
    die "expected one managed begin marker in $zshrc; found $begin_count"
  [ "$end_count" -eq 1 ] ||
    die "expected one managed end marker in $zshrc; found $end_count"

  zsh -n "$zshrc" || die "zsh syntax validation failed: $zshrc"

  note "PASS: token exists, is non-empty, and has private permissions"
  note "PASS: exactly one managed SSH wrapper is installed"
  note "PASS: zsh syntax is valid"
  note "Next: reconnect SSH or run 'source ~/.zshrc', then 'claude auth status'."
}

uninstall_zsh_wrapper() {
  local zshrc="$1"
  local backup_base="$2"
  local temporary
  local backup
  local mode
  local begin_count
  local end_count

  [ -f "$zshrc" ] || {
    note "zshrc is missing; no wrapper to remove: $zshrc"
    return
  }

  begin_count="$(managed_marker_count "$MANAGED_BEGIN" "$zshrc")"
  end_count="$(managed_marker_count "$MANAGED_END" "$zshrc")"
  if [ "$begin_count" -eq 0 ] && [ "$end_count" -eq 0 ]; then
    note "managed SSH wrapper is not installed: $zshrc"
    return
  fi
  [ "$begin_count" -eq 1 ] && [ "$end_count" -eq 1 ] ||
    die "managed markers are malformed in $zshrc"

  temporary="$(mktemp "${zshrc}.tmp.XXXXXX")"
  trap 'rm -f "${temporary:-}"' EXIT
  render_zsh_without_managed_block "$zshrc" "$temporary"
  printf '\n' >> "$temporary"

  mode="$(stat -f '%Lp' "$zshrc")"
  chmod "$mode" "$temporary"
  zsh -n "$temporary" || die "generated zsh configuration failed syntax validation"

  backup="$(backup_zshrc "$zshrc" "$backup_base")"
  mv "$temporary" "$zshrc"
  temporary=""
  trap - EXIT
  note "removed managed SSH wrapper: $zshrc"
  note "backup: $backup"
}

parse_args() {
  [ "$#" -gt 0 ] || {
    usage
    exit 1
  }

  COMMAND="$1"
  shift

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --token-file)
        [ "$#" -ge 2 ] || die "--token-file requires a path"
        TOKEN_SOURCE="$2"
        shift 2
        ;;
      --delete-token)
        DELETE_TOKEN=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "unknown option: $1"
        ;;
    esac
  done

  case "$COMMAND" in
    install)
      [ "$DELETE_TOKEN" -eq 0 ] || die "--delete-token is valid only with uninstall"
      ;;
    check)
      [ -z "$TOKEN_SOURCE" ] || die "--token-file is valid only with install"
      [ "$DELETE_TOKEN" -eq 0 ] || die "--delete-token is valid only with uninstall"
      ;;
    uninstall)
      [ -z "$TOKEN_SOURCE" ] || die "--token-file is valid only with install"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown command: $COMMAND"
      ;;
  esac
}

main() {
  parse_args "$@"
  require_supported_environment

  local token_destination="$HOME/.config/claude/ssh-oauth-token"
  local zshrc_entry="$HOME/.zshrc"
  local zshrc
  zshrc="$(resolve_symlink_target "$zshrc_entry")"

  case "$COMMAND" in
    install)
      install_token "$token_destination"
      install_zsh_wrapper "$zshrc" "$zshrc_entry"
      check_installation "$token_destination" "$zshrc"
      ;;
    check)
      check_installation "$token_destination" "$zshrc"
      ;;
    uninstall)
      uninstall_zsh_wrapper "$zshrc" "$zshrc_entry"
      if [ "$DELETE_TOKEN" -eq 1 ]; then
        rm -f "$token_destination"
        note "deleted token: $token_destination"
      else
        note "retained token: $token_destination"
      fi
      ;;
  esac
}

main "$@"
